# Generated by Django 4.2 on 2023-04-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkapp', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
