# Generated by Django 4.2 on 2023-04-17 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkapp', '0003_post_author_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profile_option',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
