# Generated by Django 4.2 on 2023-04-22 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkapp', '0007_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Work',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
