# Generated by Django 4.2 on 2023-04-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkapp', '0009_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='image',
            field=models.ImageField(upload_to='profile_picture/'),
        ),
    ]
