# Generated by Django 4.2 on 2023-04-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkapp', '0010_alter_profileimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileimage',
            old_name='user',
            new_name='author',
        ),
        migrations.AddField(
            model_name='profileimage',
            name='author_username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
