# Generated by Django 4.2 on 2023-04-23 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkapp', '0013_alter_profileimage_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio',
        ),
        migrations.AlterField(
            model_name='profileimage',
            name='image',
            field=models.ImageField(upload_to='profile_picture/'),
        ),
    ]
